[versions]
agp = "8.5.0"
kotlin = "1.9.24"
pluginPublish = "1.1.0"

# Testing
junit = "5.9.2"
truth = "1.4.2"

[libraries]
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }

# Testing
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
